from cantilever_beam import CantileverBeam
from carre import Carre
from reduced_problem import ReducedProblem
from robot_arm import RobotArm
from rosenbrock import Rosenbrock
from tensor_product import TensorProduct
from torsion_vibration import TorsionVibration
from water_flow import WaterFlow
from welded_beam import WeldedBeam
from wing_weight import WingWeight
