ipython nbconvert --to html sampling.ipynb
ipython nbconvert --to html problems.ipynb
ipython nbconvert --to html SMT.ipynb
ipython nbconvert --to html RMTS.ipynb
ipython nbconvert --to html RBF.ipynb
ipython nbconvert --to html PA2.ipynb
ipython nbconvert --to html Nomenclature.ipynb
ipython nbconvert --to html LS.ipynb
ipython nbconvert --to html Kriging.ipynb
ipython nbconvert --to html KPLS.ipynb
ipython nbconvert --to html KPLSK.ipynb
ipython nbconvert --to html GEKPLS.ipynb
ipython nbconvert --to html IDW.ipynb