"""
Author: Hugo Reimeringer <hugo.reimeringer@onera.fr>
"""

import unittest
from smt.utils.sm_test_case import SMTestCase

import numpy as np
from scipy import special
from smt.sampling_methods import LHS
from smt.applications import PODI


def cos_coeff(i: int, x: np.ndarray):
    """Generates the i-th coefficient for the one-dimension problem."""

    a = 2 * i // 2 - 1
    return a * x[:, 0] * np.cos(i * x[:, 0])


def Legendre(i: int, t: np.ndarray):
    """Generates the i-th Legendre's polynom and returns its values at input values."""

    return special.legendre(i)(t)


class Test(SMTestCase):
    """Class to test Proper Orthogonal Decomposition and Interpolation (PODI) surrogate models based."""

    def setUp(self):
        """Sets up the test case for the tests."""

        self.nt = 40
        xlimits = np.array([[0, 4]])
        sampling = LHS(xlimits=xlimits)
        self.xt = sampling(self.nt)

        self.ny = 100
        self.t = np.linspace(-1, 1, self.ny)

        self.n_modes_test = 10

        self.nn = 15
        self.xn = sampling(self.nn)

        self.nv = 10 * self.nt
        self.xv = sampling(self.nv)

        self.x = np.concatenate((self.xt, self.xv))

        def pb_1d(x: np.ndarray) -> np.ndarray:
            """
            Constructs the one-dimension problem

            Parameters
            ----------
            x : np.ndarray
                Array containing the snapshot values : each row corresponds to a specific snapshot.

            Returns
            -------
            database : np.ndarray
                Snapshot matrix, each row corresponds to the values of our problem at a specific snapshot.
            """

            u0 = np.zeros((1, self.ny))

            alpha = np.zeros((x.shape[0], self.n_modes_test))
            for i in range(self.n_modes_test):
                alpha[:, i] = cos_coeff(i, x)

            V_init = np.zeros((self.ny, self.n_modes_test))
            for i in range(self.n_modes_test):
                V_init[:, i] = Legendre(i, self.t)

            V = Test.gram_schmidt(V_init.T).T
            database = u0 + np.dot(alpha, V.T)
            self.basis_original = V.T

            return database

        self.full_database = pb_1d(self.x)
        self.database = self.full_database[: self.nt]

    @staticmethod
    def gram_schmidt(input_array: np.ndarray) -> np.ndarray:
        """Static method that performs the  Gram-Schmidt's algorithm."""

        basis = np.zeros_like(input_array)
        for i in range(len(input_array)):
            basis[i] = input_array[i]
            for j in range(i):
                basis[i] -= (
                    np.dot(input_array[i], basis[j])
                    / np.dot(basis[j], basis[j])
                    * basis[j]
                )
            basis[i] /= np.linalg.norm(basis[i])
        return basis

    @staticmethod
    def check_projection(
        basis_original: np.ndarray, basis_pod: np.ndarray
    ) -> np.ndarray:
        """
        Computes the residue's norm of the projection of the pod basis on the subspace generated by the problem basis.

        Parameters
        ----------
        basis_original : np.ndarray

        basis_pod : np.ndarray

        Returns
        -------
        norm_residue : np.ndarray
            norm of the left residue
        """

        norm_residue = np.zeros(len(basis_pod))

        projection = np.dot(basis_pod, basis_original.T).dot(basis_original)

        for i in range(len(projection)):
            proj = projection[i]
            norm_residue[i] = np.linalg.norm(basis_pod[i] - proj)
        return norm_residue

    def test_predict(self):
        """Tests the predict methods."""

        sm = PODI()

        sm.compute_pod(self.database, tol=1)
        sm.set_interp_options("KRG")
        sm.set_training_values(self.xt)
        sm.train()

        var_xt = sm.predict_variances(self.xt)

        np.testing.assert_allclose(var_xt, np.zeros(var_xt.shape), atol=1e-6)

        mean_xn = sm.predict_values(self.xn)
        var_xn = sm.predict_variances(self.xn)
        deriv_xn = sm.predict_derivatives(self.xn, 0)

        assert mean_xn.shape == (self.nn, self.ny)
        assert var_xn.shape == (self.nn, self.ny)
        assert deriv_xn.shape == (self.nn, self.ny)

        mean_xv = sm.predict_values(self.xv)

        diff = self.full_database[self.nt :] - mean_xv
        rms_error = [np.sqrt(np.mean(diff[i] ** 2)) for i in range(diff.shape[0])]

        np.testing.assert_allclose(rms_error, np.zeros(self.nv), atol=1e-2)

    def test_set_options(self):
        """Tests the method that sets the interpolations options settings."""

        sm = PODI()
        sm.compute_pod(self.database, n_modes=5)
        options = [
            {
                "poly": "quadratic",
                "corr": "matern32",
                "pow_exp_power": 0.38,
                "theta0": [1e-1],
            }
        ]
        sm.set_interp_options("KRG", options)

        sm_list = sm.get_interp_coef()
        for interp_coeff in sm_list:
            for key in options[0].keys():
                assert interp_coeff.options[key] == options[0][key]

    def test_pod(self):
        """Tests the computing of the pod."""

        sm = PODI()

        sm.compute_pod(self.database, tol=1)
        assert sm.get_ev_ratio() == 1

        n_modes = sm.get_n_modes()
        assert n_modes <= self.n_modes_test

        basis_pod = sm.get_left_basis()
        assert basis_pod.shape == (self.nt, self.ny)

        singular_values = sm.get_singular_values()
        assert len(singular_values) == self.nt
        np.testing.assert_allclose(
            singular_values[n_modes:], np.zeros(self.nt - n_modes), atol=1e-6
        )

        norm_residue = Test.check_projection(self.basis_original, basis_pod)
        np.testing.assert_allclose(norm_residue[:n_modes], np.zeros(n_modes), atol=1e-6)


if __name__ == "__main__":
    unittest.main()
